#! /usr/bin/env sh
patat -w slides.md
# lookatme -e file_loader,terminal,image_ueberzug --live slides.md
# lookatme stuff V
# styles:
#   style: rrt
#   margin:
#     left: 30
#     right: 30
# extensions:
#   - file_loader
#   - image_ueberzug
#   - terminal
